name: GrumPHP

on: [push]
jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 3
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.2', '7.3', '7.4']
        composer-options: ['', '--prefer-lowest']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: xdebug, mbstring #optional
    - name: Check PHP Version
      run: php -v
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer update --prefer-dist --no-progress --no-suggest ${{matrix.composer-options}}
    - name: Run test suite
      run: vendor/bin/grumphp run
